import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navigate from "@/components/Navigate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ antialiased bg-[#FFFDFA] w-full`}
      >
        <div className="w-full fixed top-12 z-10 ">
         <div className="w-full max-w-xl mx-auto ">
            <Navigate />
         </div>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
