import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Navigate from "@/components/Navigate";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ antialiased bg-[#FFFDFA] w-full`}
      >
        <div className="w-full fixed top-12 z-10 ">
         <div className="w-full max-w-xl mx-auto ">
            <Navigate />
         </div>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
